name: Doxygen Documentation

# Rulează doar când dai push la un tag care începe cu 'v'
on:
  push:
    tags:
      - 'v*'

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4   # <-- Schimbat aici

    # ... (restul rămâne la fel) ...

    

    - name: Install Doxygen
      run: |
        sudo apt-get update
        sudo apt-get install -y doxygen

    - name: Run Doxygen
      # Se mută în folderul de laborator unde ai Doxyfile-ul
      working-directory: laboratories/cicd-documentation
      run: doxygen Doxyfile

    - name: Upload Documentation Artifact
      uses: actions/upload-artifact@v4   # <-- Schimbat aici
      with:
        name: doxygen-html
        path: laboratories/cicd-documentation/html/3

        